#!/usr/bin/env bash
# overnight_exit_study.sh
#
# One-shot runner for the overnight exit-strategy study:
#   1. Backfill all available session pickles through the new detector
#   2. Run the full exit-strategy comparison
#   3. Save a dated report to logs/exit_studies/
#   4. Push the refreshed snapshot to aiedge.trade
#
# Usage:
#   ./tools/overnight_exit_study.sh                # all available pickles
#   ./tools/overnight_exit_study.sh --date 2026-04-17   # single date
#   ./tools/overnight_exit_study.sh --skip-push    # don't POST to site
#
# Output:
#   logs/exit_studies/YYYY-MM-DD_exit_study.txt
#   logs/exit_studies/YYYY-MM-DD_backfill.log
#   (snapshot POSTed to aiedge.trade unless --skip-push)

set -euo pipefail
cd "$(dirname "$0")/.."

STAMP=$(date +%Y-%m-%d_%H%M)
OUT_DIR="logs/exit_studies"
mkdir -p "$OUT_DIR"

BACKFILL_LOG="$OUT_DIR/${STAMP}_backfill.log"
STUDY_REPORT="$OUT_DIR/${STAMP}_exit_study.txt"

SKIP_PUSH=0
BACKFILL_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-push) SKIP_PUSH=1; shift ;;
    --date)      BACKFILL_ARGS+=("--date" "$2"); shift 2 ;;
    *)           BACKFILL_ARGS+=("$1"); shift ;;
  esac
done

echo "════════════════════════════════════════════════════════════════════"
echo "  Overnight exit study — ${STAMP}"
echo "════════════════════════════════════════════════════════════════════"

echo
echo "STEP 1/3  Backfill Pattern Lab through new detector"
echo "          (logs to $BACKFILL_LOG)"
python3 backfill_pattern_lab.py "${BACKFILL_ARGS[@]}" 2>&1 | tee "$BACKFILL_LOG"

echo
echo "STEP 2/3  Simulate every exit strategy on every detection"
echo "          (report to $STUDY_REPORT)"
{
  echo "Exit strategy study — ${STAMP}"
  echo "Generated by tools/overnight_exit_study.sh"
  echo
  echo "=== All live detections ==="
  python3 compare_exits.py
  echo
  echo "=== Last 30 days only ==="
  python3 compare_exits.py --days 30
} | tee "$STUDY_REPORT"

if [[ $SKIP_PUSH -eq 0 ]]; then
  echo
  echo "STEP 3/3  Push refreshed snapshot to aiedge.trade"
  python3 pattern_lab_api.py --push https://www.aiedge.trade/api/patterns
else
  echo
  echo "STEP 3/3  Skipped (--skip-push)"
fi

echo
echo "Done."
echo "  Report:   $STUDY_REPORT"
echo "  Backfill: $BACKFILL_LOG"
